### ISSUE TITLE
implement login api

### ISSUE THREAD

**Issue by Matthew19-24** [WIGteam/WIG-Android#19]
In this ticket we will be implementing all login functions to the Android Application via the backend API. This ticket will also add the scanner activity back into the application.

**Blocked By**
- [ ] [setup endpoint container](https://github.com/WIGteam/WIG-Server/issues/3)
- [x] [create login api](https://github.com/WIGteam/WIG-Server/issues/2)
- [x] [create local storage file](https://github.com/WIGteam/WIG-Android/issues/26)

**Acceptance Criteria**
1. User is able to login via username and password
2. Incorrect username or password will fail to login
3. User will stay logged in when app closes and starts up from new state

**Local Storage Reference**

Save Token
```kotlin
val storeToken = StoreToken(this@Login)
storeToken.saveToken(email)
``` 

Use Token
```kotlin
lifecycleScope.launch {
  val storeToken = StoreToken(this@CONTEXT)
  val tokenFlow: Flow<String?> = storeToken.getToken

  tokenFlow.collect { token ->
    if (token != null && token.isNotBlank()) {
       // handle use of 'token' here
    } else {
      // handle no token here
    }
  }
}
```
